[tools]
fzf = "latest"
lua = "5.1.5"
neovim = "latest"
node = "24.4.1"
python = "3.12.9"
ripgrep = "latest"
starship = "latest"
zoxide = "latest"
ghq = "latest"
fd = "latest"
eza = "latest"
bat = "latest"
chezmoi = "latest"
lazygit = "latest"
rust = "latest"
go = "latest"
yarn = "latest"
